/// *
// * This Java source file was generated by the Gradle 'init' task.
// */
// package seongjun.cms;
//
// import org.junit.Test;
// import static org.junit.Assert.*;
//
// public class AppTest {
// @Test public void testAppHasAGreeting() {
// ClinetApp classUnderTest = new ClinetApp();
// assertNotNull("app should have a greeting", classUnderTest.getGreeting());
// }
// }
